accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name = "accounts/login.html"), name='login'),
    path('logout/', LogoutView.as_view(template_name = "accounts/logout.html"), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
]

photo/urls.py
from django.urls import path
from .views import PhotoCreate, PhotoDelete, PhotoDetail, PhotoList, PhotoUpdate, PhotoLike, PhotoFavorite
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings

app_name = 'photo'

urlpatterns = [
    path("create/", PhotoCreate.as_view(), name = 'create'),
    path("like/<int:photo_id>", PhotoLike.as_view(), name = 'like'),
    path("favorite/<int:photo_id>", PhotoFavorite.as_view(), name = 'favorite'),
    path("update/<int:pk>/", PhotoUpdate.as_view(), name = 'update'),
    path("delete/<int:pk>/", PhotoDelete.as_view(), name = 'delete'),
    path("detail/<int:pk>/", PhotoDetail.as_view(), name = 'detail'),
    path("", PhotoList.as_view(), name = 'index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Photo(models.Model) :
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'user')
    text = models.TextField(blank = True)
    image = models.ImageField(upload_to = 'timeline_photo/%y/%m/%d')
    created = models.DateTimeField(auto_now_add = True)
    update = models.DateTimeField(auto_now = True)

    Like = models.ManyToManyField(User, related_name='like_post', blank=True)
    favorite = models.ManyToManyField(User, related_name='favorite_post', blank=True)

    def __str__(self) :
        return "text : "+self.text

    class Meta :
        ordering = ['-created']

    def get_image_url(self) :
        return '%s%s' %(settings.MEDIA_URL, self.image)

    def get_absolute_url(self):
        return reverse('photo:detail', args=[self.id])

accounts/views.py
from django.shortcuts import render

# Create your views here.

photo/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from .models import Photo
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.views.generic.base import View
from django.http import HttpResponseForbidden
from urllib.parse import urlparse

# Create your views here.

class PhotoList(ListView) :
    model = Photo
    template_name_suffix = '_list'

class PhotoCreate(CreateView) :
    model = Photo
    fields = ['author', 'text', 'image']
    template_name_suffix = '_create'
    success_url = '/'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form' : form})

class PhotoUpdate(UpdateView) :
    model = Photo
    fields = ['author', 'text', 'image']
    template_name_suffix = '_update'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '수정할 권한이 없습니다.')
            return HttpResponseRedirect('/')
        else:
            return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)

class PhotoDelete(DeleteView) :
    model = Photo
    template_name_suffix = '_delete'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '삭제할 권한이 없습니다.')
            return HttpResponseRedirect('/')
        else:
            return super(PhotoDelete, self).dispatch(request, *args, **kwargs)

class PhotoDetail(DetailView) :
    model = Photo
    template_name_suffix = '_detail'

class PhotoLike(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.object.get(pk=photo_id)
                user = request.user
                if user in photo.like.all():
                    photo.like.remove(user)
                else:
                    photo.like.add(user)

            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)

class PhotoFavorite(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.object.get(pk=photo_id)
                user = request.user
                if user in photo.favorite.all():
                    photo.favorite.remove(user)
                else:
                    photo.favorite.add(user)
            return HttpResponseRedirect('/')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <div class="alert alert-primary" role="alert">
            Please enter your login information.
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="login" class="btn btn-outline-primary">
        </form>
    </div>
    <div class="col"></div>

</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <div class="alert alert-primary" role="alert">
            로그아웃 되었습니다.
        </div>
        <a href="{% url 'accounts:login' %}" class="btn btn-outline-success">login 하기</a>
    </div>
    <div class="col"></div>

</div>
{% endblock %}

photo/templates/photo/photo_create.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
        <div class="col-12 col-xl-8 col-md-8">
            <div class="alert alert-primary" role="alert">
                모든 부분을 다 채워주세요!!
            </div>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {{form.as_p}}
                <input accept="image/jpeg" type="submit" value="Upload" class="btn btn-primary">
            </form>
        </div>
    <div class="col"></div>
</div>
{% endblock %}

photo/templates/photo/photo_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="alert alert-primary" role="alert">
    진짜로 {{ object }}를 삭제하시겠습니까?
</div>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete Ok">
</form>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-4">
        <div class="card" style="width : 30rem;">
            <img src="{{ object.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">

                <h5 calss="card-title">{{ object.author }}</h5>
                <p calss="card-text">{{ object.text }}</p>
            </div>
            <ul class="list-group list-group-flush">
                    {% if user.is_authenticated %}
                    <li class="list-group-item">
                        <a herf="{% url 'photo:like' object.id %}" class="float-left btn-like {% if user in object.like.all %} active {% endif %}">좋아요!</a>
                        {% if object.like.all.count %}
                        <span class = "float-left">
                            {{ object.like.all.count }}
                        </span>
                        {% endif %}
                        <a herf="{% url 'photo:favorite' object.id %}" class="float-right btn-favorite {% if user in object.favorite.all %} active {% endif %}">저장하기!</a>
                    </li>
                    {% endif %}
                    </div>
            </ul>
            <div class="card-body">
                <li class="list-group-item">생성일 : {{ object.created }}</li>
                <li class="list-group-item">수정일 : {{ object.update }}</li>
            </ul>
            <div class="card-body">
                <a href="{% url 'photo:update' object.id %}" calss="card-link">수정하기</a>
                <a href="{% url 'photo:delete' object.id %}" calss="card-link">삭제하기</a>
            </div>
        </div>
    </div>

    <div class="col"></div>
</div>
{% endblock %}

photo/templates/photo/photo_list.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-5">
            {% for object in object_list %}

            <div class="card">
                <div class="card-header">
                    {{ object.author}}
                </div>
                    <img scr="{{ object.image.url }}" class="card_img_top" alt="...">
                <div class="card-body">
                    
                    <p class="card-text"> {{ object.text }} </p>
                </div>
                <ul class ="list-group list-group-flush">
                    {% if user.is_authenticated %}
                    <li class="list-group-item">
                        <a herf="{% url 'photo:like' object.id %}" class="float-left btn-like {% if user in object.like.all %}active{% endif %}">좋아요!</a>
                        {% if object.like.all.count %}
                        <span class = "float-left">
                            {{ object.like.all.count }}
                        </span>
                        {% endif %}
                        <a herf="{% url 'photo:favorite' object.id %}" class="float-right btn-favorite {% if user in object.favorite.all %}active{% endif %}">저장하기!</a>
                    </li>
                    {% endif %}
                    <li class="list-group-item">생성일 : {{ object.created }}</li>
                </ul>
                <div class="card-body">
                    
                    <a href="{% url 'photo:detail' object.id %}" class="card-link">댓글달기</a>
                    <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                    <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>

                </div>

            </div>
            {% endfor %}

        </div>

        <div class="col"></div>
    </div>
</div>
{% endblock %}

photo/templates/photo/photo_update.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
         <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}